### ISSUE TITLE
FeatureManager.IsEnabledAsync(nameof(MyFlags.FlagName)) does not return the current value

### ISSUE THREAD

**Issue by lightpeak** [microsoft/FeatureManagement-Dotnet#105]
Hello

_featureManager.IsEnabledAsync(flagName) does not return the current value while the CacheExpirationInterval is just 5 seconds.
When we trigger a sentinel key the feature flag does update, but we want to avoid using the sentinel for this.

![image](https://user-images.githubusercontent.com/31926380/99265881-7c0a9700-2822-11eb-9031-80cede7f7f7f.png)
![image](https://user-images.githubusercontent.com/31926380/99265909-84fb6880-2822-11eb-822f-708415cda4e4.png)
![image](https://user-images.githubusercontent.com/31926380/99265919-888eef80-2822-11eb-9836-505a8c7c9517.png)
Blazor server page:
![image](https://user-images.githubusercontent.com/31926380/99265951-90e72a80-2822-11eb-8166-11657ec63787.png)
![image](https://user-images.githubusercontent.com/31926380/99265972-95134800-2822-11eb-9d03-e7ef8443cf73.png)
But it's not Blazor specific, APIControllers don't get the right value aswel:
![image](https://user-images.githubusercontent.com/31926380/99266172-c724aa00-2822-11eb-93a8-41fbd3c0c42b.png)
![image](https://user-images.githubusercontent.com/31926380/99266294-e7ecff80-2822-11eb-9933-8c7ef380fddd.png)

Thank you in advance and kind regards

**Comment by lightpeak** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.3.0" />
    <PackageReference Include="Microsoft.Azure.AppConfiguration.AspNetCore" Version="4.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.AzureKeyVault" Version="3.1.10" />
    <PackageReference Include="Microsoft.FeatureManagement" Version="2.2.0" />
    <PackageReference Include="Microsoft.FeatureManagement.AspNetCore" Version="2.2.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Dlw-DistributedConfig.Shared\Dlw-DistributedConfig.Shared.csproj" />
  </ItemGroup>
</Project>
```

**Comment by jimmyca15** [comment]
Is the 5 seconds that was called out important here? Are you able to get the latest version of the feature flag if you request the page some time after 5 seconds, say 10? Are you able to provide a minimal repro app?

**Comment by lightpeak** [comment]
Hi Jimmy

Thank you for reaching out. I found an older issue and comment (https://github.com/microsoft/FeatureManagement-Dotnet/issues/30#issuecomment-564790868) in which you gave **the solution** to our problem:
> The configuration selector and feature flag selector are independent

Since we were using labeled feature flags we had to specify them in the feature flag options.

```
options.Select(KeyFilter.Any, context.HostingEnvironment.EnvironmentName);
options.UseFeatureFlags(options => {
    options.CacheExpirationInterval = TimeSpan.FromSeconds(5);                                
    options.Label = context.HostingEnvironment.EnvironmentName;                                
});
```

This is working perfectly!

Thank you and kind regards,
Jelle

**Comment by andyhammar** [comment]
How does the `Label` field on the UseFeatureFlags(options =>) relate to the `option.Select` on the AppConfiguration?
I'm PoC'ing this currently and sometimes it's enough for me to specify _EnvironmentName_ on the options.Select() and the feature filters will obey that, but sometimes it does not and I have to specify the .Label in UseFeatureFlags as well.

So, should it be enough to do `options.Select(KeyFilter.Any, context.HostingEnvironment.EnvironmentName)` and have the feature flags load for that label as well, or should `.Label` always be set too?

Thanks
@jimmyca15

**Comment by jimmyca15** [comment]
@andyhammar

> How does the Label field on the UseFeatureFlags(options =>) relate to the option.Select on the AppConfiguration?

Feature flags are specialized settings in Azure App Configuration. At the root, they are no different then other settings that are queried with `AzureAppConfigurationOptions.Select`. So when you use `AzureAppConfigurationOptions.Select(KeyFilter.Any, context.HostingEnvironment.EnvironmentName)` feature flags with the corresponding label will be pulled down.

UseFeatureFlags does two things, it enables a query for feature flags (starts with ".appconfig.featureflag/") and it sets up feature flags to be refreshed. The query for feature flags that I mentioned uses the `Label` property to decide what label the feature flags should be pulled from.

**Comment by andyhammar** [comment]
Aha, thanks for the quick response @jimmyca15 .

So did I understand this scenario correctly?

1) In AzureAppConfig I have a few key-values defined, and a feature - both are defined for "PreProd":
![image](https://user-images.githubusercontent.com/1713268/120688733-a7459280-c4a3-11eb-88f8-a250f531e89e.png)

2) The feature toggle's values for "PreProd" include a group named "PreProd":
![image](https://user-images.githubusercontent.com/1713268/120688822-c04e4380-c4a3-11eb-8ae2-45f4bd0e6cac.png)

3) When I run with this code (=Select has "PreProd", but FeatureFlags options does not (intentionally commented out):
![image](https://user-images.githubusercontent.com/1713268/120688936-d9ef8b00-c4a3-11eb-857c-f978bd9d0a20.png)

4) And finally the config's loaded from Azure looks like below.
My interpretation of this is:
a) The key-value config of "TestSettingInPreProdOnly" is there because of the 'Select' in my Program.cs
b) The feature filters does not have the "PreProd" settings, and that it because I did not specify that as the UseFeatureFlags Label - and the UseFeatureFlags has resulted in yet another download of the feature flags only for "blank" label?

I was expecting a "Select" on the config to pull everything for that keyFilter (=PreProd) - and FeatureFlags to just load feature flags from what's been loaded by AppConfig.

Hence to load FeatureFlag for environment (or label) specifics - one _has_ to specify the Label on the UseFeatureFlags (since that does independent refresh of those) - and it works independently of the config read from AppConfig?

Sorry for lots of questions in one - but it's basically just a single question :) Thanks a bunch!
(happy to submit a PR on the getting started docs, I think the FF Label needs to be mentioned)
