### ISSUE TITLE
Allow client-side toggling of flags

### ISSUE THREAD

**Issue by chriskuech** [microsoft/FeatureManagement-Dotnet#106]
I believe client-side toggling of flags is an essential part of flighting, as they enable opting in and verifying before flighting out the flag.  This library appears to support the proper hooks for this (deriving flags from `HttpContext` in an `IFeatureFilter`), but still requires consumers to implement this custom.  Given the security implications of letting clients dictate control-flow, I believe this should be implemented in this library, as to avoid consumers "rolling their own" security around this.  Such an `IFeatureFilter` might use a separate definition of flags (to ensure no overlap between public/client-side-togglable flags and private flags), or might integration with ASP.NET Core security and require a specific Authentication Scheme or Authorization Policy.

**Comment by jimmyca15** [comment]
Hello @chriskuech I'm having some trouble digesting the issue here. It sounds like a feature request. Do you have a specific scenario or example app that might help convey your idea?

**Comment by chriskuech** [comment]
Yes this is a feature request, not a bug.

I'm not sure if your team is familiar with the (now decommissioned) Microsoft-internal Carbon service for managing feature switches, but it allowed you to set feature switches as URL parameters.  Something along the lines of this:

```
?myswitch=1
```

**Comment by jimmyca15** [comment]
It sounds like this feature request: https://github.com/microsoft/FeatureManagement-Dotnet/issues/89

**Comment by chriskuech** [comment]
Not sure I 100% understand #89, but they do sounds similar, but I would be nervous to allow clients to set _any_ feature switch though.

**Comment by jimmyca15** [comment]
Okay, I think I understand better now. 

What you want is completely achievable today through the implementation of the `IFeatureFilter` interface. Here is an example of a [custom feature filter](https://github.com/microsoft/FeatureManagement-Dotnet/blob/424c13ae5af1f6e735c2080052f97e1683a299c0/examples/FeatureFlagDemo/BrowserFilter.cs#L26) that uses the user agent to enable features. You can base a feature filter off of this that inspects the query string rather than the user agent.

#89 is a feature-request asking for the capability to register a feature-filter to run for all features. Today, if this is desired, then the feature management configuration needs to be set up so that every feature references the feature filter.

**Comment by jimmyca15** [comment]
Did that suggestion resolve the original issue for you @chriskuech ?
