### ISSUE TITLE
No method of identifying feature flag by label

### ISSUE THREAD

**Issue by ksoich** [microsoft/FeatureManagement-Dotnet#196]
If a Feature Flag has the same name, but different label the SDK gives no context what label the flag was returned from. In fact, a feature flag will be overwritten in the SDK. 
(This will happen if the flag has the same name, but different key as well)

**Example**
App Config Feature Flags
![image](https://user-images.githubusercontent.com/99049491/188671161-f7de65ff-c589-4117-8fa0-ccd01d779266.png)

Startup
```          
            builder.ConfigurationBuilder.AddAzureAppConfiguration(options =>
            {
                options.Connect(Environment.GetEnvironmentVariable("AppConfig"))
                    .Select("_")
                    .UseFeatureFlags(options =>
                    {
                        options.Select("*", "Release Toggles");
                        options.Select("*", "Experiment Toggles");
                    });
            });
```

Return list of Flags
```
                // Get list of feature flags
                var featureNamesAsyncEnum = _featureManagerSnapshot.GetFeatureFlagNamesAsync();
```
Output: FlagOne

_featureManagerSnapshot.GetFeatureFlagNamesAsync() is only returning 1 feature flag despite there being two feature flags. On top of this, there is no indication, via label name or key name, what the feature flag is.

**Comment by zhenlan** [comment]
The `Microsoft.FeatureManagement` is built on top of `IConfiguration`. Any configuration provider can be a source of feature flags as long as it provides the configuration in the format that `Microsoft.FeatureManagement` expects. Label is not a concept in `IConfiguration`. Azure App Configuration is just one of the providers for `IConfiguration`. You have to decide which feature flag to use if they have the same key but different labels. This behavior is by design.
