### ISSUE TITLE
How to Get All Feature Flags?

### ISSUE THREAD

**Issue by steven-rothwell** [microsoft/FeatureManagement-Dotnet#234]
My scenario is that we have an API that is used to hide our connection string for UI that needs to check if a feature flag is enabled/disabled.  Otherwise, we would be making calls directly to Azure in our Angular app.  Instead, we have this API that will be the go-between for all of the SPAs in our system.

How can I get all feature flags?

When I do:
```
options.UseFeatureFlags(featureOptions =>
{
  featureOptions.CacheExpirationInterval = TimeSpan.FromMinutes(5);
}
```
If I do not specify a `featureOptions.Label`, and I check what feature flags are available via `_featureManager.GetFeatureNamesAsync()`, I get things like "AllowedHosts", "APPDATA", "applicationName", and other nonsense that are not actually feature flags. For me to get actually feature flags returned, I have to set `featureOptions.Label` to a label that an actual feature flag has.  I get that in normal circumstances, you want to limit how many feature flags are retrieved and cached.  But, since this API is a go-between for our entire system, I don't want to have to update the code every time someone adds a new label to a feature flag.

So, how can I just get all of the feature flags independent of what their labels are?

**Comment by rossgrambo** [comment]
Hello @steven-rothwell ,

Our FeatureFlagDemo example shows one way to do this. You can see what they do [here](https://github.com/microsoft/FeatureManagement-Dotnet/blob/main/examples/FeatureFlagDemo/Program.cs#L29-L36).

```
o.Connect(settings["AppConfiguration:ConnectionString"]);
o.Select(KeyFilter.Any);
o.UseFeatureFlags();
```

Or you could select using the full feature flag prefix `.appconfig.featureflag/*`.

This is only if you don't care about the other configuration settings and only want Feature Flags. 

Hope this helps! Let me know if it doesn't work for you.

**Comment by steven-rothwell** [comment]
@rossgrambo, thanks for replying so quickly.  I tried `o.Select(KeyFilter.Any);` and `o.Select(.appconfig.featureflag/*);` both after Connect and within UseFeatureFlags, but I'm still getting the  "AllowedHosts", "APPDATA", "applicationName", things returned.  To note, our Feature Flags are not included in the Configuration Explorer.  The team that handles this wanted to keep them separate.

**Comment by rossgrambo** [comment]
Could I see what provider you're using?

Essentially- all `GetFeatureNamesAsync` does is call the provider's `GetAllFeatureDefinitionsAsync`. Our default provider reads from the `FeatureManagement` section of the Configuration. So I believe the issue is either-
1. The configuration has these misc. keys like "AllowedHosts" under the "FeatureManagement" section. 
2. Y'all are using a custom provider that doesn't filter like this. 

Referencing our [Custom Provider Section](https://github.com/microsoft/FeatureManagement-Dotnet#custom-feature-providers) of the readme, could this be the issue?

**Comment by steven-rothwell** [comment]
This is my Program.cs:
```
builder.Configuration.AddAzureAppConfiguration(options =>
{
    options.Connect(builder.Configuration.GetValue<string>("FeatureFlags:ConnectionString"))
        .ConfigureRefresh(refreshOptions =>
            refreshOptions.Register(OurFeatureFlag.Sentinel, refreshAll: true));

    options.UseFeatureFlags(featureOptions =>
    {
        featureOptions.CacheExpirationInterval = TimeSpan.FromHours(24);
        featureOptions.Select("TryingToGetAll");
    });
});
...
builder.Services.AddAzureAppConfiguration();
builder.Services.AddFeatureManagement()
    .AddFeatureFilter<UserFilter>();
...
app.UseAzureAppConfiguration();
```

My appsettings.json file is simply:
```
"FeatureFlags": {
    "ConnectionString": "#{ReadonlySharedConfigConnectionString}"
  }
```

If I specify a legit label like` featureOptions.Label = "testapi"; `instead of `featureOptions.Select("TryingToGetAll");`, it properly returns all of the feature flags with that label.

**Comment by jimmyca15** [comment]
Hello @steven-rothwell 

First off to address:

> If I do not specify a featureOptions.Label, and I check what feature flags are available via _featureManager.GetFeatureNamesAsync(), I get things like "AllowedHosts", "APPDATA", "applicationName", and other nonsense that are not actually feature flags.

This happens when you enumerate feature flags when none have been defined. The system looks at the top level of configuration and thinks that the top level settings are feature flags. This issue has a bit more information on [that behavior](https://github.com/microsoft/FeatureManagement-Dotnet/issues/144).

---

Regarding your question of "How can I get all feature flags?". It looks like you are using the Azure App Configuration configuration provider and want to select flags from every label at startup of your application.

Getting settings from **all** labels is [not supported](https://github.com/Azure/AppConfiguration-DotnetProvider/blob/9a76d2a1b43d137e139e329a575eee09641e51d3/src/Microsoft.Extensions.Configuration.AzureAppConfiguration/FeatureManagement/FeatureFlagOptions.cs#LL43C1-L44C1).

The reason is that it can lead to indeterministic behavior at run time. Whenever a feature flag exists with multiple labels (same name, different label), only one can end up in the feature management system. If the application is selecting all labels, there is no explicit way to decide which label of the feature flag should win. To combat this, we require explicit composition of labels, that way it is deterministic how settings are overridden.

Something like below
```
    .Select(label: LabelFilter.Null) // Get feature flags with the default (null) label
    .Select(label: "prod") // Take feature flags with the 'prod' label. Any existing flags with the same name with the default label will be overridden.
```
The current way to handle new labels is to update your application whenever a new label may exist and ensure to select that label taking care of the order in which it is specified for overriding purposes.

**Comment by steven-rothwell** [comment]
I completely understand what you mean about it not being deterministic as to which feature flag overwrote others if they shared the same name, but had a different label. It would be nice to leave that up to the user. Could give a warning in the description, but for users like us, who keep feature flag names unique, we could get all feature flags without worrying about them being overwritten.

One thing I don't understand is, if we did include feature flags in our configuration, and I used Ross's suggestion above to get all of the feature flags.
`o.Select(KeyFilter.Any);` and `o.Select(.appconfig.featureflag/*);`
Wouldn't it also be nondeterministic as to what feature flags were overwritten?

**Comment by rossgrambo** [comment]
Your `appsettings.json` configuration would be overwritten with the selected flags from the provider. It's deterministic because we know which features are defined and what their values are. Which means we know what the result of `isEnabledAsync` will be. The issue is when we don't know what the result will be. For example, let's say these are defined in App Configuration:

label=null
```
Beta=false
```

label=demo
```
Beta=true
```

Regardless of your local definition of Beta (or if you have one at all), if we pull down both of these at the same time, only one of these will be used. When you call `isEnabledAsync("Beta")`, we don't know which one was loaded first/last/overrode the other.

**Comment by steven-rothwell** [comment]
Do you not have that same issue even without worrying about local feature flags in the appsettings?  Let's say we had our feature flags in the Configuration and I pulled them in via `o.Select(.appconfig.featureflag/*);`.  As you said, that would overwrite my local appsettings.  But, Azure allows me to create feature flags that have the same name, but have different labels.  So, in the Azure Configuration, I could have:

```
Name:                    Label:                    Enabled:
Beta                     LabelA                    true
Beta                     LabelB                    false
```

In this scenario `isEnabledAsync("Beta")` would still not be deterministic since I did not give the Configuration an order in which to get them, I got them all via `o.Select(.appconfig.featureflag/*);`

Since there is a nondeterministic way of getting all of the feature flags via Configuration, it seems odd to not allow it when getting feature flags when they are not in the Configuration.

**Comment by rossgrambo** [comment]
Yes, that would have the same issue if my suggestion worked across labels. My suggestion of `o.Select(.appconfig.featureflag/*);` only works on a single label. Unless otherwise specified, it would only return features for the label `null`. Meaning in your example, neither of those `Beta` features would be pulled down. It would however pull down:

```
Name:                    Label:                    Enabled:
Beta                     null/default              true
```

My suggestions do not solve the multiple label case. I misunderstood the question when suggesting those.

**Comment by steven-rothwell** [comment]
Completely understand, thank you for clarifying.
