### ISSUE TITLE
Targeting evaluation is CPU dependent.

### ISSUE THREAD

**Issue by jimmyca15** [microsoft/FeatureManagement-Dotnet#403]
Targeting evaluation uses BitConvert.ToInt32 as seen [here](https://github.com/microsoft/FeatureManagement-Dotnet/blob/5dfdb23c22eecc6662afc4700966113b20e1f822/src/Microsoft.FeatureManagement/Targeting/ContextualTargetingFilter.cs#L162). According to `ToInt32`'s [documentation](https://learn.microsoft.com/en-us/dotnet/api/system.bitconverter.toint32?view=net-8.0), the result is dependent upon the CPU's endianness. 

Targeting evaluation should be consistent across CPU architectures. Given the current documented and intended usage is server scenarios, which typically run on x86, I propose to use a replacement that would give results consistent with `BitConvert.ToInt32` run on x86 systems.

**Comment by rossgrambo** [comment]
Not sure if there's a good replacement. We could explicitly check and reverse the bits?

```csharp
if (BitConverter.IsLittleEndian)
{
    Array.Reverse(bytes);
}
```

**Comment by zhiyuanliang-ms** [comment]
@rossgrambo I think the method you proposed is fine. I don't have any better idea. 

BTW, X86 and other common CPU architectures are all little-endian. So we'd better treat big-endian as special case.

**Comment by jimmyca15** [comment]
Sounds reasonable, however no need to reverse the whole array. Only the bytes used for the int32 are needed.

**Comment by zhiyuanliang-ms** [comment]
This issue also exists in Java FM: https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/spring/spring-cloud-azure-feature-management/src/main/java/com/azure/spring/cloud/feature/management/filters/TargetingFilter.java#L256

The default endianness used by ByteBuffer is big-endian: https://docs.oracle.com/javase/8/docs/api/java/nio/ByteBuffer.html
@mrm9084 

The python FM is fine since it explicitly uses little-endian:
https://github.com/microsoft/FeatureManagement-Python/blob/main/featuremanagement/_defaultfilters.py#L86
